# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanFran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('A', 'LA'), ('B', 'SJ'), ('C', 'FR'), ('D', 'AN')], max_length=1)),
                ('date', models.CharField(max_length=6)),
                ('time', models.CharField(max_length=6)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
    ]
