# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
