# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanFranTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('A', 'LA'), ('B', 'SJ'), ('C', 'FR'), ('D', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=6)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
