# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sf',
            name='time',
        ),
    ]
