# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20170821_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaheimTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BakersfieldTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BurbankTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FresnoTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GilroyTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='KingstonTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LosAngelesTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MercedTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MilroyTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrangeCountyTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PalmdaleTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SanFranciscoTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SanJoseTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=7)),
                ('seats', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='SanFranTrain',
        ),
    ]
