# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20170822_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaheimtrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bakersfieldtrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='burbanktrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fresnotrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gilroytrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kingstontrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='losangelestrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mercedtrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='milroytrain',
            name='time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='milroytrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orangecountytrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PD'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='palmdaletrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sanfranciscotrain',
            name='time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='sanfranciscotrain',
            name='to',
            field=models.CharField(choices=[('MILROY', 'ML'), ('SAN JOSE', 'SJ'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sanjosetrain',
            name='to',
            field=models.CharField(choices=[('SAN FRANCISCO', 'SF'), ('MILROY', 'ML'), ('GILROY', 'GL'), ('MERCED', 'MR'), ('FRESNO', 'FR'), ('KINGSTON', 'KG'), ('BAKERSFIELD', 'BK'), ('PALMDALE', 'PL'), ('BURBANK', 'BR'), ('LOS ANGELES', 'LA'), ('ORANGE COUNTY', 'OC'), ('ANAHEIM', 'AN')], max_length=20),
        ),
    ]
