# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20170822_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaheimtrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bakersfieldtrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='burbanktrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='fresnotrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='gilroytrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='kingstontrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='losangelestrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mercedtrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='milroytrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='orangecountytrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='palmdaletrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sanfranciscotrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sanjosetrain',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
